name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test 🧪
        run: |
          npm ci
          npm run test
  test-mac:
    runs-on: macos-12
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test 🧪
        run: |
          npm ci
          npm run test
  test-win:
    runs-on: window-2022
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Test 🧪
        run: |
          npm ci
          npm run test


